/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceOrderRouteImport } from './routes/service-order'
import { Route as NovaOrdemServicoRouteImport } from './routes/nova-ordem-servico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ServiceOrderIndexRouteImport } from './routes/service-order/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServiceOrderNewRouteImport } from './routes/service-order/new'
import { Route as ServiceOrderCustomerRouteImport } from './routes/service-order/customer'
import { Route as AdminCustomerRouteImport } from './routes/admin/customer'

const ServiceOrderRoute = ServiceOrderRouteImport.update({
  id: '/service-order',
  path: '/service-order',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaOrdemServicoRoute = NovaOrdemServicoRouteImport.update({
  id: '/nova-ordem-servico',
  path: '/nova-ordem-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceOrderIndexRoute = ServiceOrderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceOrderRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServiceOrderNewRoute = ServiceOrderNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ServiceOrderRoute,
} as any)
const ServiceOrderCustomerRoute = ServiceOrderCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => ServiceOrderRoute,
} as any)
const AdminCustomerRoute = AdminCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/nova-ordem-servico': typeof NovaOrdemServicoRoute
  '/service-order': typeof ServiceOrderRouteWithChildren
  '/admin/customer': typeof AdminCustomerRoute
  '/service-order/customer': typeof ServiceOrderCustomerRoute
  '/service-order/new': typeof ServiceOrderNewRoute
  '/admin/': typeof AdminIndexRoute
  '/service-order/': typeof ServiceOrderIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/nova-ordem-servico': typeof NovaOrdemServicoRoute
  '/admin/customer': typeof AdminCustomerRoute
  '/service-order/customer': typeof ServiceOrderCustomerRoute
  '/service-order/new': typeof ServiceOrderNewRoute
  '/admin': typeof AdminIndexRoute
  '/service-order': typeof ServiceOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/nova-ordem-servico': typeof NovaOrdemServicoRoute
  '/service-order': typeof ServiceOrderRouteWithChildren
  '/admin/customer': typeof AdminCustomerRoute
  '/service-order/customer': typeof ServiceOrderCustomerRoute
  '/service-order/new': typeof ServiceOrderNewRoute
  '/admin/': typeof AdminIndexRoute
  '/service-order/': typeof ServiceOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/nova-ordem-servico'
    | '/service-order'
    | '/admin/customer'
    | '/service-order/customer'
    | '/service-order/new'
    | '/admin/'
    | '/service-order/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/nova-ordem-servico'
    | '/admin/customer'
    | '/service-order/customer'
    | '/service-order/new'
    | '/admin'
    | '/service-order'
  id:
    | '__root__'
    | '/admin'
    | '/login'
    | '/nova-ordem-servico'
    | '/service-order'
    | '/admin/customer'
    | '/service-order/customer'
    | '/service-order/new'
    | '/admin/'
    | '/service-order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  NovaOrdemServicoRoute: typeof NovaOrdemServicoRoute
  ServiceOrderRoute: typeof ServiceOrderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service-order': {
      id: '/service-order'
      path: '/service-order'
      fullPath: '/service-order'
      preLoaderRoute: typeof ServiceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-ordem-servico': {
      id: '/nova-ordem-servico'
      path: '/nova-ordem-servico'
      fullPath: '/nova-ordem-servico'
      preLoaderRoute: typeof NovaOrdemServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-order/': {
      id: '/service-order/'
      path: '/'
      fullPath: '/service-order/'
      preLoaderRoute: typeof ServiceOrderIndexRouteImport
      parentRoute: typeof ServiceOrderRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/service-order/new': {
      id: '/service-order/new'
      path: '/new'
      fullPath: '/service-order/new'
      preLoaderRoute: typeof ServiceOrderNewRouteImport
      parentRoute: typeof ServiceOrderRoute
    }
    '/service-order/customer': {
      id: '/service-order/customer'
      path: '/customer'
      fullPath: '/service-order/customer'
      preLoaderRoute: typeof ServiceOrderCustomerRouteImport
      parentRoute: typeof ServiceOrderRoute
    }
    '/admin/customer': {
      id: '/admin/customer'
      path: '/customer'
      fullPath: '/admin/customer'
      preLoaderRoute: typeof AdminCustomerRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomerRoute: typeof AdminCustomerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomerRoute: AdminCustomerRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServiceOrderRouteChildren {
  ServiceOrderCustomerRoute: typeof ServiceOrderCustomerRoute
  ServiceOrderNewRoute: typeof ServiceOrderNewRoute
  ServiceOrderIndexRoute: typeof ServiceOrderIndexRoute
}

const ServiceOrderRouteChildren: ServiceOrderRouteChildren = {
  ServiceOrderCustomerRoute: ServiceOrderCustomerRoute,
  ServiceOrderNewRoute: ServiceOrderNewRoute,
  ServiceOrderIndexRoute: ServiceOrderIndexRoute,
}

const ServiceOrderRouteWithChildren = ServiceOrderRoute._addFileChildren(
  ServiceOrderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  NovaOrdemServicoRoute: NovaOrdemServicoRoute,
  ServiceOrderRoute: ServiceOrderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
